version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - sofia-network

  gateway-service:
    build: ./services/gateway-service
    ports:
      - "8000:8000"
    volumes:
      - ./services/gateway-service:/app
      - ./services/agent-service/mcp_tools:/app/mcp_tools
      - ./services/agent-service/common:/app/common
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AGENT_HOST=agent-service
      - AGENT_PORT=8001
      - TOOL_HOST=tool-execution-service
      - TOOL_PORT=8002
    depends_on:
      - redis
      - agent-service
      - tool-execution-service
    networks:
      - sofia-network

  agent-service:
    build:
      context: ./services/agent-service
      dockerfile: ./agent/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./services/agent-service/agent:/app/agent
      - ./services/agent-service/common:/app/common
      - ./services/agent-service/mcp_tools:/app/mcp_tools
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - arithmetic-tool
    networks:
      - sofia-network

  tool-execution-service:
    build: ./services/tool-execution-service
    ports:
      - "8002:8002"
    volumes:
      - ./services/tool-execution-service:/app
      - ./services/agent-service/clients:/app/clients
      - ./services/agent-service/common:/app/common
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - sofia-network

  arithmetic-tool:
    build:
      context: ./services/agent-service
      dockerfile: ./mcp_tools/arithmetic_tool/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./services/agent-service/mcp_tools:/app/mcp_tools
      - ./services/agent-service/common:/app/common
    environment:
      - PYTHONPATH=/app
    networks:
      - sofia-network

  client:
    build:
      context: ./services/agent-service
      dockerfile: ./clients/Dockerfile
    volumes:
      - ./services/agent-service/clients:/app/clients
      - ./services/agent-service/common:/app/common
    environment:
      - PYTHONPATH=/app
    depends_on:
      - agent-service
    networks:
      - sofia-network
    stdin_open: true
    tty: true

  web-ui:
    build:
      context: ./ui/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui/web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - sofia-network
    depends_on:
      - agent-service
      - gateway-service
    stdin_open: true
    tty: true

networks:
  sofia-network:
    driver: bridge 