version: '3'

services:
  arithmetic-tool:
    build:
      context: ./backend
      dockerfile: ./mcp_tools/arithmetic_tool/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend/mcp_tools:/app/mcp_tools
      - ./backend/common:/app/common
    environment:
      - PYTHONPATH=/app
    networks:
      - sofia-network

  agent:
    build:
      context: ./backend
      dockerfile: ./agent/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/agent:/app/agent
      - ./backend/common:/app/common
      - ./backend/mcp_tools:/app/mcp_tools
    environment:
      - PYTHONPATH=/app
    depends_on:
      - arithmetic-tool
    networks:
      - sofia-network

  client:
    build:
      context: ./backend
      dockerfile: ./clients/Dockerfile
    volumes:
      - ./backend/clients:/app/clients
      - ./backend/common:/app/common
    environment:
      - PYTHONPATH=/app
    depends_on:
      - agent
    networks:
      - sofia-network
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - sofia-network
    depends_on:
      - agent
    stdin_open: true
    tty: true

networks:
  sofia-network:
    driver: bridge 