import { Color, ColorPattern } from "./type";

export const ColorMap: Record<Color, ColorPattern> = {
    red: {
        title_color: "#ac0d0d",
        // title_color: "#000000",
        light_background: "#ffd2d8a0",
        light_background_content_node: "#ffd2d870",
        dark_background: "#3730A3",
        bg: "bg-rose-50  ",
        border: "border-rose-200  ",
        title: "text-rose-800  ",
        text: "text-rose-600  ",
        handle: "bg-rose-500",
        hover: "hover:bg-rose-100  ",
    } as ColorPattern,
    blue: {
        title_color: "#224975",
        light_background: "#c6f6fda0",
        light_background_content_node: "#c6f6fd70",
        dark_background: "#3730A3",
        bg: "bg-[#e1f5fed9]  ",
        border: "border-blue-200  ",
        title: "text-blue-800  ",
        text: "text-blue-600  ",
        handle: "bg-blue-500",
        hover: "hover:bg-blue-100  ",
    } as ColorPattern,
    yellow: {
        title_color: "#000000",
        light_background: "#fff6a5a0",
        light_background_content_node: "#fff6a570",
        dark_background: "#3730A3",
        bg: "bg-amber-50  ",
        border: "border-amber-200  ",
        title: "text-black  ",
        text: "text-amber-600  ",
        handle: "bg-amber-500",
        hover: "hover:bg-amber-100  ",
    } as ColorPattern,
    purple: {
        title_color: "#2b0094",
        light_background: "#e0d1fca0",
        light_background_content_node: "#e0d1fcb5",
        dark_background: "#3730A3",
        bg: "bg-violet-50  ",
        border: "border-violet-200  ",
        title: "text-black  ",
        text: "text-violet-600  ",
        handle: "bg-violet-500",
        hover: "hover:bg-violet-100  ",
    } as ColorPattern,
    green: {
        title_color: "#164c1a",
        light_background: "#e1f5caa0",
        light_background_content_node: "#e1f5ca78",
        dark_background: "#3730A3",
        bg: "bg-emerald-50  ",
        border: "border-emerald-200  ",
        title: "text-black  ",
        text: "text-emerald-600  ",
        handle: "bg-emerald-500",
        hover: "hover:bg-emerald-100  ",
    } as ColorPattern,
    gray: {
        title_color: "#000000",
        light_background: "#e0e0e0a0",
        light_background_content_node: "#e0e0e066",
        dark_background: "#3730A3",
        bg: "bg-gray-50  ",
        border: "border-gray-200  ",
        title: "text-black  ",
        text: "text-gray-600  ",
        handle: "bg-gray-500",
        hover: "hover:bg-gray-100  ",
    } as ColorPattern,
};
