import { Color, ColorPattern } from "./type";

export const ColorMap: Record<Color, ColorPattern> = {
    red: {
        title_color: "#ac0d0d",
        // title_color: "#000000",
        light_background: "#ffd2d8a0",
        light_background_content_node: "#ffd2d870",
        dark_background: "#3730A3",
        bg: "bg-rose-50 dark:bg-rose-900/20",
        border: "border-rose-200 dark:border-rose-800",
        title: "text-rose-800 dark:text-rose-300",
        text: "text-rose-600 dark:text-rose-400",
        handle: "bg-rose-500",
        hover: "hover:bg-rose-100 dark:hover:bg-rose-800/40",
    } as ColorPattern,
    blue: {
        title_color: "#224975",
        light_background: "#c6f6fda0",
        light_background_content_node: "#c6f6fd70",
        dark_background: "#3730A3",
        bg: "bg-[#e1f5fed9] dark:bg-blue-900/20",
        border: "border-blue-200 dark:border-blue-800",
        title: "text-blue-800 dark:text-blue-300",
        text: "text-blue-600 dark:text-blue-400",
        handle: "bg-blue-500",
        hover: "hover:bg-blue-100 dark:hover:bg-blue-800/40",
    } as ColorPattern,
    yellow: {
        title_color: "#000000",
        light_background: "#fff6a5a0",
        light_background_content_node: "#fff6a570",
        dark_background: "#3730A3",
        bg: "bg-amber-50 dark:bg-amber-900/20",
        border: "border-amber-200 dark:border-amber-800",
        title: "text-black dark:text-amber-300",
        text: "text-amber-600 dark:text-amber-400",
        handle: "bg-amber-500",
        hover: "hover:bg-amber-100 dark:hover:bg-amber-800/40",
    } as ColorPattern,
    purple: {
        title_color: "#2b0094",
        light_background: "#e0d1fca0",
        light_background_content_node: "#e0d1fcb5",
        dark_background: "#3730A3",
        bg: "bg-violet-50 dark:bg-violet-900/20",
        border: "border-violet-200 dark:border-violet-800",
        title: "text-black dark:text-violet-300",
        text: "text-violet-600 dark:text-violet-400",
        handle: "bg-violet-500",
        hover: "hover:bg-violet-100 dark:hover:bg-violet-800/40",
    } as ColorPattern,
    green: {
        title_color: "#164c1a",
        light_background: "#e1f5caa0",
        light_background_content_node: "#e1f5ca78",
        dark_background: "#3730A3",
        bg: "bg-emerald-50 dark:bg-emerald-900/20",
        border: "border-emerald-200 dark:border-emerald-800",
        title: "text-black dark:text-emerald-300",
        text: "text-emerald-600 dark:text-emerald-400",
        handle: "bg-emerald-500",
        hover: "hover:bg-emerald-100 dark:hover:bg-emerald-800/40",
    } as ColorPattern,
    gray: {
        title_color: "#000000",
        light_background: "#e0e0e0a0",
        light_background_content_node: "#e0e0e066",
        dark_background: "#3730A3",
        bg: "bg-gray-50 dark:bg-gray-900/20",
        border: "border-gray-200 dark:border-gray-800",
        title: "text-black dark:text-gray-300",
        text: "text-gray-600 dark:text-gray-400",
        handle: "bg-gray-500",
        hover: "hover:bg-gray-100 dark:hover:bg-gray-800/40",
    } as ColorPattern,
};
